apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ template "wordpress.fullname" . }}
spec:
  connectionDraining:
    drainingTimeoutSec: 60
  healthCheck:
    checkIntervalSec: 15
    port: 80
    requestPath: /
    type: HTTP
