apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "wordpress.fullname" . }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ get .Values.gcp.projectIds .Values.env }}
    iam.gke.io/gcp-service-account: {{ printf "%s@%s.iam.gserviceaccount.com" (include "wordpress.fullname" .) (get .Values.gcp.projectIds .Values.env) }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ template "wordpress.fullname" . }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ get .Values.gcp.projectIds .Values.env }}
spec:
  displayName: {{ template "wordpress.fullname" . }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: {{ template "wordpress.fullname" . }}-binding-ksa-gsa
  annotations:
    cnrm.cloud.google.com/project-id: {{ get .Values.gcp.projectIds .Values.env }}
spec:
  member: {{ printf "serviceAccount:%s.svc.id.goog[%s/%s]" (get .Values.gcp.projectIds .Values.env) .Release.Namespace (include "wordpress.fullname" .) }}
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    external: {{ printf "projects/%s/serviceAccounts/%s@%s.iam.gserviceaccount.com " (get .Values.gcp.projectIds .Values.env) (include "wordpress.fullname" .) (get .Values.gcp.projectIds .Values.env) }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: {{ template "wordpress.fullname" . }}-role-binding-sa-sql-client
  annotations:
    cnrm.cloud.google.com/project-id: {{ get .Values.gcp.projectIds .Values.env }}
spec:
  member: serviceAccount:{{ printf "%s@%s.iam.gserviceaccount.com" (include "wordpress.fullname" .) (get .Values.gcp.projectIds .Values.env) }}
  role: roles/cloudsql.client
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/{{ get .Values.gcp.projectIds .Values.env }}
