kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "wordpress.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.pvc.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
  {{- range $key, $value := .Values.pvc.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
    app: {{ template "wordpress.fullname" . }}
    version: {{ $.Chart.Version | quote }}
spec:
  storageClassName: {{ .Values.pvc.storageClass }}
  accessModes:
    - {{ .Values.pvc.accessModes}}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
