apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ get .Values.gcp.projectIds .Values.env }}
  labels:
    app: {{ template "wordpress.fullname" . }}
    version: {{ $.Chart.Version | quote }}
  name: {{ template "wordpress.fullname" . }}
spec:
  charset: {{ .Values.db.charset }}
  collation: {{ .Values.db.collation }}
  instanceRef:
    external: {{ get (get .Values.cloudsql.instances .Values.env) .Values.region }}
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ get .Values.gcp.projectIds .Values.env }}
  name: {{ template "wordpress.fullname" . }}
spec:
  instanceRef:
    external: {{ get (get .Values.cloudsql.instances .Values.env) .Values.region }}
  host: {{ .Values.db.userHost | quote }}
  password:
    value: {{ .Values.db.password }}
