apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  name: secret-{{ template "wordpress.fullname" . }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ get .Values.gcp.projectIds .Values.env }}
spec:
  replication:
    automatic: true
---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecretVersion
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ get .Values.gcp.projectIds .Values.env }}
  name: secret-{{ template "wordpress.fullname" . }}
spec:
  enabled: true
  secretData:
    value: {{ .Values.db.password }}
  secretRef:
    name: secret-{{ template "wordpress.fullname" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ template "wordpress.fullname" . }}-db
type: Opaque
data:
  db: {{ (include "wordpress.fullname" .) | b64enc }}
  host: {{ .Values.db.host | b64enc }}
  password: {{ .Values.db.password | b64enc }}
  user: {{ (include "wordpress.fullname" .) | b64enc }}
