apiVersion: v1
kind: Service
metadata:
  name: sshd
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "ssh.{{ template "wordpress.hostname" . }}"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  labels:
    app:  {{ template "wordpress.fullname" . }}-sshd
spec:
  ports:
    - port: 22
      targetPort: 22
      name: sshd-svc
  selector:
    app: sshd
    tier: admin
  type: LoadBalancer