{{- if .Values.wordpress.autoscaling.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "wordpress.fullname" . }}-ssh-vpa
  labels:
  {{- range $key, $value := .Values.wordpress.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
    app: {{ template "wordpress.fullname" . }}
    version: {{ $.Chart.Version | quote }}  
spec:
  targetRef:
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
    kind: Deployment
    name: {{ template "wordpress.fullname" . }}-sshd
  updatePolicy:
    updateMode: {{ .Values.sshd.autoscaling.updateMode }}
{{- end }}
---
{{- if .Values.wordpress.autoscaling.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "wordpress.fullname" . }}-redis-vpa
  labels:
  {{- range $key, $value := .Values.wordpress.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
    app: {{ template "wordpress.fullname" . }}
    version: {{ $.Chart.Version | quote }}  
spec:
  targetRef:
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
    kind: StatefulSet
    name: {{ template "wordpress.fullname" . }}-redis-master
  updatePolicy:
updateMode: {{ .Values.redis.autoscaling.updateMode }}
{{- end }}
