apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ template "wordpress.fullname" . }}-wp
type: Opaque
data:
  user: {{ .Values.wordpress.adminCreds.managementEmail | b64enc }}
  password: {{ .Values.wordpress.adminCreds.password | b64enc }}
