---
apiVersion: monitoring.googleapis.com/v1alpha1
kind: PodMonitoring
metadata:
  name: version-checker
  namespace: {{.Release.Namespace}}
spec:
  endpoints:
  - interval: 30s
    port: 8080
  selector:
    matchLabels:
      app: version-checker
  targetLabels:
    metadata:
    - pod
