kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-default-values
  namespace: {{.Release.Namespace}}
data:
  values.yaml: |-
    replicaCount: 1

    image:
      repository: quay.io/prometheus/alertmanager
      pullPolicy: IfNotPresent
      tag: "v0.24.0"

    ingress:
      enabled: false

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 32Mi

    podDisruptionBudget:
      minAvailable: 1

    persistence:
      enabled: true
      storageClass: "standard"
      accessModes:
        - ReadWriteOnce
      size: 50Mi

    configmapReload:
      enabled: false
