kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config-values
  namespace: {{.Release.Namespace}}
data:
  values.yaml: |-
    # config:
    #   global:
    #     resolve_timeout: 5m

    #   route:
    #     group_wait: 10s
    #     group_interval: 5m
    #     receiver: nucleus
    #     repeat_interval: 1h
    #     group_by:
    #     - namespace
    #     - application

    #   inhibit_rules:
    #   - equal:
    #     - application
    #     - alertname
    #     source_match:
    #       severity: critical
    #     target_match_re:
    #       severity: warning|info

    #   receivers:
    #     - name: nucleus
    #       webhook_configs:
    #       - send_resolved: true
    #         url: {{.Values.alertmanager.nucleus_uri | quote}}
    #         max_alerts: {{.Values.alertmanager.max_alerts}}
    #         {{- if .Values.alertmanager.nucleus_key }}
    #         http_config:
    #           authorization:
    #             type: Bearer
    #             credentials: {{.Values.alertmanager.nucleus_key | quote}}
    #         {{- end -}}
