kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config-values
  namespace: {{.Release.Namespace}}
data:
  values.yaml: |-
    config:
      global:
        resolve_timeout: 5m

      route:
        group_wait: 10s
        group_interval: 5m
        receiver: version-checker
        repeat_interval: 1h
        group_by:
        - namespace
        - application

      inhibit_rules:
      - equal:
        - application
        - alertname
        source_match:
          severity: critical
        target_match_re:
          severity: warning|info

      receivers:
        - name: version-checker
          webhook_configs:
          - send_resolved: true
            url: {{.Values.alertmanager.version_checker_uri | quote}}
            max_alerts: {{.Values.alertmanager.max_alerts}}