---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alertmanager
  namespace: {{.Release.Namespace}}
spec:
  chart:
    spec:
      chart: alertmanager
      interval: 1m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: {{.Release.Namespace}}
      version: 0.16.0
  interval: 5m

  valuesFrom:
  - kind: ConfigMap
    name: alertmanager-default-values
    valuesKey: values.yaml
  - kind: ConfigMap
    name: alertmanager-config-values
    valuesKey: values.yaml
