apiVersion: v1
kind: Secret
metadata: 
  name: ssh-secret
data: 
  ssh_password: {{ .Values.sshSecrets.ssh_password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-ssh-publickey-auth
data:
  ssh_publickey: {{ .Values.sshSecrets.ssh_publickey | b64enc }}
