apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.secretName }}
  labels:
    app.kubernetes.io/name: {{ include "jiralert.name" .}}
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/managed-by: {{ .Release.Service}}
    helm.sh/chart: {{ include "jiralert.chart" .}}
stringData:
  jiralert.yml: |-
    template: {{ .Values.config.template }}
    
    # Global defaults, applied to all receivers where not explicitly overridden. Optional.
    defaults:
      api_url: {{ .Values.config.api_url }}
      user: {{ .Values.config.user }}
      password: '{{ .Values.config.password }}'
      issue_type: {{ .Values.config.issue_type }}
      priority: {{ .Values.config.priority }}
      summary: '{{ .Values.config.summary }}'
      description: '{{ .Values.config.description }}'
      reopen_state: {{ .Values.config.reopen_state }}
      wont_fix_resolution: "{{ .Values.config.wont_fix_resolution }}"
      reopen_duration: {{ .Values.config.reopen_duration }}
      parent_jql: {{ .Values.config.parent_jql | squote }}
      parent_subtask_type: {{ .Values.config.parent_subtask_type }}
    receivers: {{ required "At least one receiver must be defined" .Values.config.receivers | toYaml | nindent 4 }}
  jiralert.tmpl: |-
  {{ .Files.Get "jiralert.tmpl" | nindent 4 }}