apiVersion: v1
kind: Service
metadata:
  name: jiralert
  labels:
    app.kubernetes.io/name: {{ include "jiralert.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "jiralert.chart" . }}
spec:
  type: {{ .Values.jiralert_service.type }}
  selector:
    name: jiralert
    app.kubernetes.io/name: {{ include "jiralert.name" .}}
    app.kubernetes.io/instance: {{ .Release.Name}}
  ports:
    - port: 9097
      targetPort: 9097
      {{ if eq .Values.jiralert_service.type "NodePort" }}
      nodePort: {{ .Values.jiralert_service.nodeport }}
      {{ end }}
