{{- range $cron, $val := .Values.cron }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  schedule: {{ .schedule | quote }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit }}
  suspend: {{ .suspend }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            cron: {{ .name }}
        spec:
          containers:
          - name: {{ .name }}
            image: {{ .image }}
            command: {{ .command }}
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: {{ .imagePullSecretsName }}
{{- end }}
