apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "litespeed.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    name: {{ template "litespeed.fullname" . }}
    userID: {{ .Values.userID | quote }}
    appID: {{ .Values.appID | quote }}
    version: {{ $.Chart.Version | quote }}
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      name: {{ template "litespeed.fullname" . }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
      maxSurge: {{ .Values.strategy.maxSurge }}
  revisionHistoryLimit: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        name: {{ template "litespeed.fullname" . }}
        userID: {{ .Values.userID | quote  }}
        appID: {{ .Values.appID | quote }}
        version: {{ .Chart.Version | quote }}
    spec:
      containers:
      - name: webserver
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- if .Values.envVar }}
        env:
        {{- range $key, $value := .Values.envVar}}
         - name: {{ $key }}
           value: {{ $value }}
        {{- end }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 7080
          name: ls-dash
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/local/lsws/bin/lswsctrl
            - 'status'
            - |
            - grep -Ee '^litespeed is running with PID [0-9]+.$'
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /login.php
            port: 7080
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
          - mountPath: /opt/ini/
            name: php-ini
          - mountPath: {{ .Values.envVar.WEB_DOCUMENT_ROOT }}
            name: home
      volumes:
      - name: home
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}
      - name: php-ini
        configMap:
          defaultMode: 420
          name: {{ template "litespeed.fullname" . }}-php-ini
      restartPolicy: {{ .Values.restartPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecretsName }}