kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pvc.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-1"
spec:
  storageClassName: {{ .Values.pvc.storageClass }}
  accessModes:
    - {{ .Values.pvc.accessModes}}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
