{{- if not .Values.ingress.issuer.letsencrypt }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "litespeed.fullname" . }}-pre-owned-tls
  labels:
    userID: {{ .Values.userID | quote }}
    appID: {{ .Values.appID | quote }}
    version: {{ .Chart.Version | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.issuer.preOwned.crt | b64enc }}
  tls.key: {{ .Values.ingress.issuer.preOwned.key | b64enc }}
{{- end }}
