apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ include "update-app-workflow.name" . }}
spec:
  template:
    serviceAccountName: {{ .Values.serviceAccount.eventSourceServiceAccount.name }}
  pubSub:
    update-app:
      jsonBody: {{ .Values.gcp.sub.jsonBody }}
      projectID: {{ .Values.gcp.pubSubProjectId }}
      topic: {{ .Values.gcp.sub.updateAppTopic }}
