apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operate-workflow-role
rules:
  - apiGroups:
      - argoproj.io
    verbs:
      - "*"
    resources:
      - workflows
      - workflowtemplates
      - cronworkflows
      - clusterworkflowtemplates
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operate-workflow-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operate-workflow-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.workflowServiceAccount.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Namespace }}-clusterrole"
rules:
  - apiGroups:
    - ""
    resources:
      - namespaces
    verbs:
      - create
      - delete
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - patch
      - list
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - watch
  - apiGroups:
      - helm.toolkit.fluxcd.io
    verbs:
      - "*"
    resources:
      - helmreleases
  - apiGroups:
      - helm.toolkit.fluxcd.io
    verbs:
      - '*'
    resources:
      - helmreleases/status
  - apiGroups:
      - source.toolkit.fluxcd.io
    verbs:
      - "*"
    resources:
      - helmrepositories
  - apiGroups:
      - iam.cnrm.cloud.google.com
    verbs:
      - create
      - delete
      - list
      - get
      - watch
    resources:
      - "*"
  - apiGroups:
      - sql.cnrm.cloud.google.com
    verbs:
      - list
      - get
      - watch
    resources:
      - sqlusers
      - sqldatabases
  - apiGroups:
      - sql.cnrm.cloud.google.com
    verbs:
      - list
      - get
      - watch
    resources:
      - sqlusers/status
      - sqldatabases/status
  - apiGroups:
      - secretmanager.cnrm.cloud.google.com
    verbs:
      - get
      - list
      - watch
    resources:
      - secretmanagersecretversions/status
  - apiGroups:
      - secretmanager.cnrm.cloud.google.com
    verbs:
      - get
      - list
      - watch
    resources:
      - secretmanagersecretversions
  - apiGroups:
      - ""
    verbs:
      - create
      - delete
    resources:
      - secrets
  - apiGroups:
    - extensions
    - apps
    resources:
    - deployments/status
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - extensions
    - apps
    resources:
    - deployments
    verbs:
    - get
    - watch
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Release.Namespace }}-crb"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Release.Namespace }}-clusterrole"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.workflowServiceAccount.name }}
    namespace: {{ .Release.Namespace }}
