apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ include "add-app-workflow.name" . }}
spec:
  template:
    serviceAccountName: {{ .Values.serviceAccount.workflowServiceAccount.name }}
  dependencies:
    - name: body
      eventSourceName: {{ include "add-app-workflow.name" . }}
      eventName: add-app
  triggers:
    - template:
        name: add-app-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: add-app-workflow-
              spec:
                serviceAccountName: {{ .Values.serviceAccount.workflowServiceAccount.name }}
                entrypoint: add-app
                arguments:
                  parameters:
                  - name: body
                  - name: app_id
                  - name: operation_id
                  - name: values
                  - name: steps
                templates:
                - name: add-app
                  steps:
                    - - name: create-ns
                        templateRef:
                          name: {{ include "add-app-workflow.name" . }}
                          template: create-ns
                    - - name: create-release
                        templateRef:
                          name: {{ include "add-app-workflow.name" . }}
                          template: helm-release
                    - - name: watch-helmrelease-readiness
                        templateRef:
                          name: {{ include "add-app-workflow.name" . }}
                          template: watch-helmrelease-readiness
                      # - name: watch-gcp-readiness-and-grant-user
                      #   templateRef:
                      #     name: {{ include "add-app-workflow.name" . }}
                      #     template: watch-gcp-readiness-and-grant-user
          parameters:
            - src:
                dependencyName: body
                dataKey: body
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: body
                dataTemplate: "application{{`{{.Input.body.app_id }}`}}"
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: body
                dataKey: body.operation_id
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: body
                dataKey: body.values
              dest: spec.arguments.parameters.3.value
            - src:
                dependencyName: body
                dataKey: body.steps
              dest: spec.arguments.parameters.4.value
