apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.eventSourceServiceAccount.name }}
  labels:
    {{- include "app-workflows.labels" . | nindent 4 }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.gcp.projectId }}
    iam.gke.io/gcp-service-account: {{ printf "%s@%s.iam.gserviceaccount.com" .Values.serviceAccount.eventSourceServiceAccount.name .Values.gcp.projectId }}
  {{- with .Values.serviceAccount.eventSourceServiceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.workflowServiceAccount.name }}
  labels:
    {{- include "app-workflows.labels" . | nindent 4 }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.gcp.projectId }}
    iam.gke.io/gcp-service-account: {{ printf "%s@%s.iam.gserviceaccount.com"  .Values.serviceAccount.workflowServiceAccount.name  .Values.gcp.projectId }}
  {{- with .Values.serviceAccount.workflowServiceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
