apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "app-workflows.labels" . | nindent 4 }}    
  name: slack-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-secret
  strategy: {}
  template:
    spec:
      serviceAccountName: {{ .Values.serviceAccount.workflowServiceAccount.name }}
      containers:
      - image: {{ .Values.slacksecret.containers.image }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.slacksecret.containers.name }}
        resources:
          requests:
{{ toYaml .Values.slacksecret.containers.resources.requests | indent 8 }}
        stdin: true
        stdinOnce: true
        volumeMounts:
          - mountPath: "/var/secrets"
            name: secrets
      volumes:
      - name: {{ .Values.slacksecret.volumes.name }}
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.slacksecret.volumes.secretProviderClass | quote }}