apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name:  {{ include "update-app-workflow.name" . }}
spec:
  serviceAccountName: {{ .Values.serviceAccount.workflowServiceAccount.name }}
  templates:
    - name: helm-release
      resource:
        action: apply
        manifest: |
          apiVersion: helm.toolkit.fluxcd.io/v2beta1
          kind: HelmRelease
          metadata:
            name: "{{`{{workflow.parameters.app_id}}`}}"
            namespace: "{{`{{workflow.parameters.app_id}}`}}"
          spec:
            interval: {{ .Values.wordpress.release.interval }}
            timeout: {{ .Values.wordpress.release.timeout }}
            chart:
              spec:
                chart: {{ .Values.wordpress.chartName }}
                sourceRef:
                  kind: HelmRepository
                  name: {{ .Values.wordpress.repositoryName }}
                  namespace: {{ .Values.wordpress.repositoryNamespace }}
                interval: {{ .Values.wordpress.release.chartInterval }}
                {{- if ne .Values.wordpress.chartVersion "latest" }}
                version: {{ .Values.wordpress.chartVersion }}
                {{- end }}
            values:
              {{`{{workflow.parameters.values}}`}}
    - name: watch-helmrelease-readiness
      container:
        image: "{{ .Values.app.imageName }}:{{ .Values.app.imageTag }}"
        command: ["python"]
        args:
        - "update_app.py"
        - {{ .Values.gcp.pubSubProjectId }}
        - "{{`{{workflow.parameters.operation_id}}`}}"
        - {{ .Values.gcp.pub.statusOperationTopic }}
        - "{{`{{workflow.parameters.app_id}}`}}"
