name: Build version-checker helm chart
on:
  push:
    branches:
      - dev
    paths:
      - "shared/version-checker/**"
      - ".github/workflows/version-checker.yaml"
      - "!shared/version-checker/Chart.yaml"
  pull_request:
    branches:
      - dev
    paths:
      - "shared/version-checker/**"
      - ".github/workflows/version-checker.yaml"

jobs:
  version-checker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: pulling the branch
      with:
        fetch-depth: 50
        token: ${{ secrets.GIT_ACTION_PAT }}

    - name: Linting Helm
      run: |
        helm lint shared/version-checker/

    - name: Setup git
      if: github.event_name == 'push'
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global url."https://oauth2:${{ secrets.GIT_ACTION_PAT }}@github.com".insteadOf https://github.com

    - name: Get new chart version
      if: github.event_name == 'push'
      run: |
        echo "VERSION=$(cat shared/version-checker/Chart.yaml | grep version | head -1 | sed -e "s/version: //" | \
        awk -F'[.]'  '{ major=$1;minor=$2;patch=$3;patch += 1;minor += patch / 20;patch = patch % 20;printf( "%d.%d.%d\n", major, minor, patch );}' )" \
        >> $GITHUB_ENV

    - name: Update chart version
      if: github.event_name == 'push'
      run: |
        sed -i 's/^version: .*$/version: '"$VERSION"'/1' shared/version-checker/Chart.yaml

    - name: Debug
      if: github.event_name == 'push'
      id: version
      run: |
        echo "::set-output name=VERSION::$(echo $VERSION)"

    # - name: Generate changelog
    #   if: github.event_name == 'push'
    #   id: Changelog
    #   uses: metcalfc/changelog-generator@v1.0.0
    #   with:
    #     myToken: ${{ secrets.GIT_ACTION_PAT }}

    # - name: Create Release
    #   if: github.event_name == 'push'
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GIT_ACTION_PAT }}
    #   with:
    #     tag_name: "version-checker-${{ env.VERSION }}"
    #     release_name: "version-checker-${{ env.VERSION }}"
    #     body: ${{ steps.Changelog.outputs.changelog }}
    #     draft: false
    #     prerelease: false

    - name: Update chart version in remote repo
      if: github.event_name == 'push'
      run: |
        git pull origin dev
        git add shared/version-checker/Chart.yaml
        git commit -m "[AUTO] update chart version"
        git push --force

    - name: Copy chart to gh-pages branch
      if: github.event_name == 'push'
      run: |
        git fetch origin gh-pages
        git checkout gh-pages -f
        git checkout dev shared/version-checker/ -f

    - name: Package and indexing Chart
      if: github.event_name == 'push'
      run: |
        helm dependency update shared/version-checker/
        helm package shared/version-checker/
        helm repo index .

    - name: Commit to branch
      if: github.event_name == 'push'
      run: |
        git restore --staged shared/version-checker/
        git add index.yaml version-checker*.tgz
        git commit -m "[AUTO] New version-checker Chart version"
        git push
